repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -lc 'mypy --config-file mypy.ini'
        language: system
        pass_filenames: false
      - id: import-linter
        name: importlinter
        entry: bash -lc 'lint-imports'
        language: system
        pass_filenames: false
