repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        additional_dependencies: []
        args: ["--config-file", "mypy.ini"]
  - repo: https://github.com/pytest-dev/pytest
    rev: 8.2.0
    hooks:
      - id: pytest
        additional_dependencies: []
        args: ["-q"]
