# Crypto AI Bot - Balanced Ruff Configuration
# Paths are relative to repo root, without 'src/' prefix
target-version = "py311"
line-length = 110

[lint]
select = [
    "E", "F", "W",       # pycodestyle + pyflakes
    "B", "C90",          # bugbear + complexity
    "I",                 # isort
    "UP",                # pyupgrade
    "S",                 # bandit security
    "N",                 # pep8-naming
    "SIM", "RET", "PERF",# simplify + return + performance
    "ASYNC",             # async/await patterns
    "A",                 # flake8-builtins
    "BLE",               # blind-except
    "C4",                # comprehensions
    "ARG",               # unused arguments
    "TRY",               # exception handling
]

ignore = [
    "E501",              # line too long (controlled by line-length)
    "E731",              # lambda assignment
    "B904",              # raise without from
    "B008",              # function call in default argument
    "S101",              # assert statements
    "A003",              # builtin attribute shadowing
    "ARG002",            # unused method argument
    "TRY003",            # long exception messages
]

[lint.per-file-ignores]
# Tests
"tests/**/*.py" = [
    "S", "ARG", "BLE001", "SIM", "N802"
]

# Scripts
"scripts/**/*.py" = [
    "T20", "S"
]

# CLI tools - note: no src/ prefix
"crypto_ai_bot/cli/*.py" = [
    "T20", "BLE001", "TRY301", "ARG001"
]

# App layer
"crypto_ai_bot/app/server.py" = [
    "ARG001", "ASYNC109", "B008"
]

"crypto_ai_bot/app/compose.py" = [
    "BLE001", "C901"
]

"crypto_ai_bot/app/adapters/telegram*.py" = [
    "BLE001", "TRY301", "S101"
]

"crypto_ai_bot/app/subscribers/*.py" = [
    "BLE001", "ARG001"
]

# Core application
"crypto_ai_bot/core/application/orchestrator.py" = [
    "C901", "BLE001"
]

"crypto_ai_bot/core/application/use_cases/execute_trade.py" = [
    "TRY301", "BLE001"
]

"crypto_ai_bot/core/application/protective_exits.py" = [
    "BLE001", "PERF401"
]

"crypto_ai_bot/core/application/events_topics.py" = [
    "N812"
]

# Core domain
"crypto_ai_bot/core/domain/strategies/*.py" = [
    "C901"
]

"crypto_ai_bot/core/domain/signals/*.py" = [
    "C901"
]

# Infrastructure
"crypto_ai_bot/core/infrastructure/brokers/*.py" = [
    "BLE001", "ARG", "C901", "TRY301", "S324"
]

"crypto_ai_bot/core/infrastructure/storage/*.py" = [
    "S608", "BLE001"
]

"crypto_ai_bot/core/infrastructure/storage/migrations/*.py" = [
    "S608", "E501"
]

"crypto_ai_bot/core/infrastructure/settings.py" = [
    "S105", "S106", "C901"
]

# Utils - critical files have no ignores
"crypto_ai_bot/utils/decimal.py" = []
"crypto_ai_bot/utils/pnl.py" = []

# Package inits
"**/__init__.py" = [
    "F401", "F403"
]

[lint.isort]
known-first-party = ["crypto_ai_bot"]
known-third-party = ["ccxt", "redis", "prometheus_client", "fastapi", "pydantic", "httpx"]
combine-as-imports = true
force-single-line = false
force-sort-within-sections = true