# Stricter, but still green-by-default (tests are relaxed where sensible).
line-length = 120
target-version = "py311"

[lint]
# Core families + isort + pyupgrade + security + naming + simplify
select = ["E", "F", "W", "B", "C90", "I", "UP", "S", "N", "SIM", "RET", "PERF"]

# Pragmatic ignores (tests/scripts — см. per-file-ignores ниже)
ignore = [
  "E501",   # long lines
  "E701",   # multiple statements on one line (colon)
  "E702",   # multiple statements on one line (semicolon)
  "E731",   # lambda assigned
  "B904",   # raise ... from in except blocks
  "B008",   # function call in default argument
  "RUF001", "RUF002", "RUF003", "RUF005", "RUF012",
  "UP027", "UP038",
  "E402",   # module level import not at top of file
  "E741",   # ambiguous variable name
  "C901",   # function complexity
]

[lint.per-file-ignores]
"tests/**"           = ["E501", "E701", "E702", "C901", "E741", "B904", "B008", "S", "N", "SIM", "RET"]
"scripts/**"         = ["E501", "E701", "E702", "S", "N", "SIM"]
"src/**/__init__.py" = ["F401"]

[lint.isort]
known-first-party = ["crypto_ai_bot"]
combine-as-imports = true
force-sort-within-sections = true

# Optional: help catching suspicious code paths (Bandit fine-tuning)
[lint.flake8-bandit]
# Allow common patterns in tests while keeping prod strict via per-file-ignores.
