# .ruff.toml — профиль "зелёный CI без правок кода"
line-length = 120
target-version = "py311"

[lint]
# Оставляем базовые ошибки синтаксиса/логики и безопасные проверки.
# Специфичные группы, которые шумят на кириллице/советы апгрейда, сейчас не включаем.
select = ["E", "F", "B", "C90"]  # без "I", "UP", "RUF"

# Временные игноры "шумных" правил, которые уже всплывали
ignore = [
  "E501",   # длина строки
  "E701",   # несколько выражений на строке (if:)
  "E702",   # несколько выражений на строке (;)
  "E731",   # lambda assigned
  # Ниже оставлены на тот случай, если их включат локально: 
  "RUF001", "RUF002", "RUF003", "RUF005", "RUF012",
  "UP027", "UP038",
  "E402",   # импорт не сверху
  "E741",   # односимвольные имена
  "C901",   # сложность функций
]

[lint.per-file-ignores]
"tests/**"   = ["E501", "E701", "E702", "C901", "E741"]
"scripts/**" = ["E501", "E701", "E702"]
"src/**/__init__.py" = ["F401"]  # разрешаем реэкспорт

# isort-настройки оставлены на будущее (когда вернём группу "I")
[lint.isort]
known-first-party = ["crypto_ai_bot"]
combine-as-imports = true
force-sort-within-sections = true
