# .ruff.toml — конфигурация Ruff (для отдельного файла конфигурации)

target-version = "py311"
line-length = 100
exclude = [
    "venv", ".venv", ".tox", "dist", "build",
    "**/__pycache__", ".mypy_cache", ".ruff_cache", ".pytest_cache",
    "**/migrations/*.sql",
]

[lint]
# Оставляем важные проверки (ошибки/баги/импорты/апгрейды)
select = [
  "F",   # реальные ошибки (pyflakes)
  "E", "W",   # базовые ошибки/предупреждения (pycodestyle)
  "B",       # bugbear: потенциальные баги
  "UP",      # безопасные апгрейды синтаксиса
  "I",       # порядок импортов (isort)
  "A",       # затенение builtins
  "C90",     # сложность (mccabe)
  "RUF",     # ruff-специфические
]

# Глушим «шум» (рус/эмодзи, однострочники, вкусовщина) — почистим позже
ignore = [
  "RUF001", "RUF002", "RUF003",   # русские/похожие символы в строках
  "E701", "E702",                 # однострочные if / ; в конце строки
  "C401", "C417",                 # set/dict comprehensions — вкусовщина
  "SIM102", "SIM105", "SIM108", "SIM118",
  "UP038",                        # isinstance(..., dict|list) — не критично
  "PT018",                        # придирки к assert/докстрингам
]

[lint.mccabe]
max-complexity = 12

[lint.isort]
combine-as-imports = true
known-first-party = ["crypto_ai_bot"]
