# Stricter, but still green-by-default (tests are relaxed where sensible).
line-length = 120
target-version = "py311"

[lint]
# Expand families: add I (isort) and UP (pyupgrade) to catch drift.
select = ["E", "F", "W", "B", "C90", "I", "UP"]

# Keep pragmatic ignores. E501 intentionally ignored; tests/scripts looser via per-file-ignores.
ignore = [
  "E501",   # long lines
  "E701",   # multiple statements on one line (colon)
  "E702",   # multiple statements on one line (semicolon)
  "E731",   # lambda assigned
  "B904",   # raise ... from in except blocks
  "B008",   # function call in default argument
  "RUF001", "RUF002", "RUF003", "RUF005", "RUF012",
  "UP027", "UP038",
  "E402",   # module level import not at top of file
  "E741",   # ambiguous variable name
  "C901",   # function complexity
]

[lint.per-file-ignores]
"tests/**"          = ["E501", "E701", "E702", "C901", "E741", "B904", "B008"]
"scripts/**"        = ["E501", "E701", "E702"]
"src/**/__init__.py" = ["F401"]

[lint.isort]
known-first-party = ["crypto_ai_bot"]
combine-as-imports = true
force-sort-within-sections = true
