# .ruff.toml — компактная конфигурация, чтобы CI стал зелёным
line-length = 120
target-version = "py311"

[lint]
select = ["E", "F", "I"]                   # базовые ошибки + сортировка импортов
ignore = [
  "E501",   # длина строки — позже поправим автоформатером
  "C901",   # сложность функций — вынесем позже
  "RUF009", # вызовы в датакласс-значениях по умолчанию
  "B008",   # вызовы в значениях параметров по умолчанию
  "B904",   # raise from в except — включим позже
  "E402",   # импорт не сверху (вспом. модуль)
  "E741",   # односимвольные имена (l) — поправим позже
]

[lint.per-file-ignores]
"tests/**"   = ["E501", "C901", "B008", "B904", "E741"]
"scripts/**" = ["E501"]
"src/**/__init__.py" = ["F401"]  # разрешаем реэкспорт

[lint.isort]
known-first-party = ["crypto_ai_bot"]
combine-as-imports = true
force-sort-within-sections = true
