version: "3.9"
services:
  web:
    build: .
    container_name: cab-web
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  worker:
    build: .
    container_name: cab-worker
    command: ["python", "-m", "crypto_ai_bot.cli.health_monitor"]
    env_file: .env
    depends_on:
      - web
      - redis
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: cab-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  data:
