version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports:
    - 6379:6379
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped
  app:
    build: .
    env_file: .env
    depends_on:
      redis:
        condition: service_healthy
    ports:
    - 8000:8000
    environment:
      EVENT_BUS_URL: redis://redis:6379/0
    volumes:
    - ./data:/app/data
    healthcheck:
      test:
      - CMD-SHELL
      - curl -fsS http://localhost:8000/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 30
    restart: unless-stopped
