[project]
name = "crypto-ai-bot"
version = "0.1.0"
description = "Crypto AI Bot (FastAPI + brokers + signals + SQLite)"
readme = "README.md"
requires-python = ">=3.10"
authors = [{ name = "you" }]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = "-q"

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
check_untyped_defs = true
warn_unused_ignores = true
