# .ruff.toml — lint config (Ruff)
line-length = 100
target-version = "py310"

[lint]
select = ["E","F","W","I","B","C4","PIE","PT","RUF"]
ignore = ["E501"]  # already set line-length

[lint.per-file-ignores]
# allow using 'os' only here
"src/crypto_ai_bot/core/config/env_reader.py" = ["E402"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"

# Ban direct ENV usage across the codebase
[lint.flake8-tidy-imports.banned-api]
"os.getenv" = { msg = "Use EnvReader instead of os.getenv (see core/config/env_reader.py)" }
"os.environ" = { msg = "Use EnvReader instead of os.environ (see core/config/env_reader.py)" }
