# Crypto AI Bot — Ruff config (v1.0-beta)
target-version = "py311"
line-length = 110

[lint]
select = [
  "E","F","W",          # pycodestyle + pyflakes
  "I",                  # isort (импорты)
  "B","C90",            # bugbear + complexity
  "UP",                 # pyupgrade
  "S",                  # bandit (security)
  "N",                  # pep8-naming
  "SIM","RET","PERF",   # упрощения, return, perf
  "ASYNC",              # async/await
  "A",                  # builtins
  "BLE",                # blind-except
  "TRY",                # exceptions
]

ignore = [
  "E501",   # длина строки (контролируем line-length)
  "S101",   # assert в тестах
  "TRY003", # длинные тексты в исключениях
]

[lint.per-file-ignores]
# Tests
"tests/**/*.py" = ["S","ARG","BLE001","SIM"]

# CLI
"src/crypto_ai_bot/cli/*.py" = ["T20","BLE001"]

# App layer
"src/crypto_ai_bot/app/*.py" = ["BLE001","C901"]
"src/crypto_ai_bot/app/telegram*.py" = ["BLE001","TRY301"]

# Core application
"src/crypto_ai_bot/core/application/orchestrator.py" = ["C901"]
"src/crypto_ai_bot/core/application/use_cases/execute_trade.py" = ["TRY301"]

# Infrastructure
"src/crypto_ai_bot/core/infrastructure/brokers/*.py" = ["BLE001"]
"src/crypto_ai_bot/core/infrastructure/macro_sources/*.py" = ["BLE001"]  # НОВОЕ
"src/crypto_ai_bot/core/infrastructure/settings.py" = ["S105","S106"]

# Пакетные __init__.py
"**/__init__.py" = ["F401","F403"]

[lint.isort]
known-first-party = ["crypto_ai_bot"]
combine-as-imports = true