# НОВЫЙ ФАЙЛ: ops/prometheus/alertmanager.yml
global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 12h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'telegram-critical'

receivers:
- name: 'default'
  # Базовый receiver (без уведомлений)
  
- name: 'telegram-critical'
  # TODO: настроить Telegram webhook
  webhook_configs:
  - url: 'http://localhost:8000/alerts/telegram'
    send_resolved: true