groups:
- name: trading_critical
  rules:
  # === КРИТИЧЕСКИЕ АЛЕРТЫ ===
  - alert: TradingSystemDown
    expr: up{job="crypto-ai-bot"} == 0
    for: 1m
    labels: {severity: critical}
    annotations:
      summary: "Торговая система недоступна"
      description: "Приложение не отвечает более 1 минуты"

  - alert: DatabaseConnectionLost
    expr: increase(db_connection_errors_total[5m]) > 3
    for: 2m
    labels: {severity: critical}
    annotations:
      summary: "Потеряно соединение с БД"
      description: "{{ $value }} ошибок подключения к БД за 5 минут"

  - alert: OrderExecutionFailed
    expr: rate(orders_fail_total[5m]) > 0.1
    for: 3m
    labels: {severity: critical}
    annotations:
      summary: "Высокий процент неудачных ордеров"
      description: "{{ $value }} неудачных ордеров в минуту"

  - alert: PositionSyncLost
    expr: (time() - position_last_sync_timestamp) > 600
    for: 1m
    labels: {severity: critical}
    annotations:
      summary: "Потеряна синхронизация позиций"
      description: "Позиции не синхронизировались {{ $value }} секунд"

- name: trading_warnings
  rules:
  # === ПРЕДУПРЕЖДЕНИЯ ===
  - alert: BrokerHighLatency
    expr: histogram_quantile(0.95, rate(broker_latency_seconds_bucket[5m])) > 2.0
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "Высокая латентность биржи"
      description: "P95 латентность: {{ $value }}s"

  - alert: EventBusDLQGrowing
    expr: increase(bus_dlq_total[10m]) > 10
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "Растет очередь недоставленных событий"
      description: "{{ $value }} событий в DLQ за 10 минут"

  - alert: RiskBlocksFrequent
    expr: rate(risk_blocks_total[15m]) > 0.2
    for: 10m
    labels: {severity: warning}
    annotations:
      summary: "Частые блокировки risk-менеджера"
      description: "{{ $value }} блокировок в минуту"

  - alert: IdempotencyHighUsage
    expr: rate(orders_duplicate_total[5m]) > 0.05
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "Много дублирующих запросов"
      description: "{{ $value }} дубликатов ордеров в минуту"

- name: trading_performance
  rules:
  # === ПРОИЗВОДИТЕЛЬНОСТЬ ===
  - alert: DecisionLatencyHigh
    expr: histogram_quantile(0.99, rate(latency_decision_seconds_bucket[5m])) > 5.0
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "Медленные торговые решения"
      description: "P99 время принятия решения: {{ $value }}s"

  - alert: OrderLatencyHigh
    expr: histogram_quantile(0.95, rate(latency_order_seconds_bucket[5m])) > 3.0
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "Медленное исполнение ордеров"
      description: "P95 время исполнения ордера: {{ $value }}s"

  - alert: PerformanceBudgetExceeded
    expr: rate(performance_budget_single_exceeded_total[5m]) > 0.1
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "Превышения performance budget"
      description: "{{ $value }} превышений в минуту для {{ $labels.kind }}"

- name: trading_business
  rules:
  # === БИЗНЕС ЛОГИКА ===
  - alert: PnLDriftSignificant
    expr: abs(current_pnl_calculated - current_pnl_exchange) > (position_size_usd * 0.02)
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "Расхождение в расчете PnL"
      description: "Разница между расчетным и биржевым PnL: {{ $value }}"

  - alert: SlippageExcessive
    expr: avg_over_time(order_slippage_bps[15m]) > 50
    for: 10m
    labels: {severity: warning}
    annotations:
      summary: "Высокое проскальзывание"
      description: "Среднее проскальзывание: {{ $value }} bps"

  - alert: DrawdownLimit
    expr: current_drawdown_pct > 5.0
    for: 1m
    labels: {severity: critical}
    annotations:
      summary: "Превышен лимит просадки"
      description: "Текущая просадка: {{ $value }}%"

- name: infrastructure
  rules:
  # === ИНФРАСТРУКТУРА ===
  - alert: HighMemoryUsage
    expr: (process_resident_memory_bytes / 1024 / 1024) > 512
    for: 5m
    labels: {severity: warning}
    annotations:
      summary: "Высокое потребление памяти"
      description: "Используется {{ $value }}MB памяти"

  - alert: TimeDriftExcessive
    expr: abs(time_drift_ms) > 5000
    for: 2m
    labels: {severity: warning}
    annotations:
      summary: "Большой дрейф времени"
      description: "Дрейф времени: {{ $value }}ms"

  - alert: CircuitBreakerOpen
    expr: circuit_breaker_state{state="open"} == 1
    for: 1m
    labels: {severity: warning}
    annotations:
      summary: "Circuit breaker разомкнут"
      description: "Circuit breaker {{ $labels.name }} в состоянии open"