groups:
- name: trading_slo
  rules:
  - alert: BrokerRateLimitStorm
    expr: sum(rate(broker_http_429[5m])) > 5
    for: 2m
    labels: {severity: warning}
    annotations:
      summary: "Много 429 от биржи"
      description: "broker_http_429 > 5/5m"

  - alert: RetrySpike
    expr: sum(rate(broker_retry_temp[5m])) > 10
    for: 2m
    labels: {severity: warning}
    annotations:
      summary: "Всплеск ретраев"
      description: "broker_retry_temp > 10/5m"

  - alert: PendingOrdersStuck
    expr: avg_over_time(app_pending_orders[10m]) > 0
    for: 10m
    labels: {severity: critical}
    annotations:
      summary: "Ордеры застряли в pending"
      description: "Есть pending-ордера дольше 10 минут"
