from __future__ import annotations

# Единая точка истинны темы — импортируем реестр и прокидываем константы наружу.
from crypto_ai_bot.core.application import events_topics as EVT

# Брокер/ордера
ORDER_EXECUTED = EVT.ORDER_EXECUTED
ORDER_FAILED = EVT.ORDER_FAILED

# Торговый шаг (high-level)
TRADE_COMPLETED = EVT.TRADE_COMPLETED
TRADE_FAILED = EVT.TRADE_FAILED
TRADE_SETTLED = EVT.TRADE_SETTLED
TRADE_SETTLEMENT_TIMEOUT = EVT.TRADE_SETTLEMENT_TIMEOUT
TRADE_BLOCKED = EVT.TRADE_BLOCKED
TRADE_PARTIAL_FOLLOWUP = EVT.TRADE_PARTIAL_FOLLOWUP

# Здоровье и наблюдаемость
WATCHDOG_HEARTBEAT = EVT.WATCHDOG_HEARTBEAT
HEALTH_REPORT = EVT.HEALTH_REPORT

# Риски/бюджеты
RISK_BLOCKED = EVT.RISK_BLOCKED
BUDGET_EXCEEDED = EVT.BUDGET_EXCEEDED

# Оценка/решение (локальные рабочие темы)
EVALUATION_STARTED = "evaluation.started"
DECISION_EVALUATED = "decision.evaluated"

# Сверки
RECONCILIATION_COMPLETED = EVT.RECONCILIATION_COMPLETED
RECONCILE_POSITION_MISMATCH = EVT.RECONCILE_POSITION_MISMATCH

# Оркестратор
ORCH_AUTO_PAUSED = EVT.ORCH_AUTO_PAUSED
ORCH_AUTO_RESUMED = EVT.ORCH_AUTO_RESUMED

# Safety
DMS_TRIGGERED = EVT.DMS_TRIGGERED
DMS_SKIPPED = EVT.DMS_SKIPPED

# Alertmanager (Prometheus/Grafana)
ALERTS_ALERTMANAGER = EVT.ALERTS_ALERTMANAGER

# Ошибки брокера
BROKER_ERROR = EVT.BROKER_ERROR
