name: ci

on:
  push:
  pull_request:

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff isort

      - name: Lint (ruff)
        run: ruff check .

      - name: Import order (isort check only)
        run: isort --check-only .

      - name: Smoke run (paper mode, no network)
        env:
          MODE: paper
          EXCHANGE: gateio
          SYMBOL: BTC/USDT
          FIXED_AMOUNT: "50"
          DATA_DIR: ./data
          IDEMPOTENCY_BUCKET_MS: "60000"
          IDEMPOTENCY_TTL_SEC: "600"
        run: |
          python - <<'PY'
          import os, asyncio
          os.environ.setdefault("MODE","paper")
          from crypto_ai_bot.app.compose import build_container
          from crypto_ai_bot.core.application.use_cases.eval_and_execute import eval_and_execute
          async def main():
              c = build_container()
              # один dry-run тик (force buy с фиксированной суммой)
              order = await eval_and_execute(
                  symbol=os.getenv("SYMBOL","BTC/USDT"),
                  storage=c.storage, broker=c.broker, bus=c.bus, exchange=c.settings.EXCHANGE,
                  fixed_quote_amount=c.settings.FIXED_AMOUNT,
                  idempotency_bucket_ms=c.settings.IDEMPOTENCY_BUCKET_MS,
                  idempotency_ttl_sec=c.settings.IDEMPOTENCY_TTL_SEC,
                  force_action="buy",
                  risk_manager=c.risk, protective_exits=c.exits, settings=c.settings,
                  fee_estimate_pct=c.settings.FEE_PCT_ESTIMATE,
              )
              assert order is not None
              print("smoke_ok", order.client_order_id)
          asyncio.run(main())
          PY
