name: build-and-check   # <— новое имя workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-test:            # <— имя job, оставляем таким
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install
        run: |
          python -m pip install -U pip wheel
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install -e .
          pip install pytest httpx fastapi ruff mypy import-linter

      - name: Ruff
        run: ruff check .

      - name: Mypy (soft-fail)
        env:
          PYTHONPATH: src
        run: mypy src/ || echo "::warning ::mypy reported issues"

      - name: Import Linter (soft-fail)
        run: lint-imports -c importlinter.ini || echo "::warning ::import-linter reported issues"

      - name: Pytest
        env:
          MODE: paper
          EXCHANGE: gateio
          SYMBOL: BTC/USDT
          DB_PATH: ":memory:"
          PYTHONPATH: src
        run: pytest -q
