name: ci
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install -U pip wheel
          pip install -e .
          pip install pytest httpx fastapi
      - name: Run tests
        env:
          MODE: paper
          EXCHANGE: gateio
          SYMBOL: BTC/USDT
          DB_PATH: ":memory:"
        run: pytest -q
