name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project + tools
        run: |
          python -m pip install -U pip wheel
          pip install -e .
          pip install ruff mypy import-linter

      - name: Ruff (lint)
        run: ruff check src

      - name: Mypy (soft types)
        run: mypy src || true

      - name: Import Linter (architecture)
        run: lint-imports --config importlinter.ini

      - name: Smoke import compose (no network)
        env:
          MODE: paper
          EXCHANGE: gateio
          SYMBOL: BTC/USDT
          FIXED_AMOUNT: "10"
          PRICE_FEED: fixed
          FIXED_PRICE: "100"
        run: |
          python - <<'PY'
          from crypto_ai_bot.app.compose import build_container
          c = build_container()
          assert c.settings.MODE.lower() in ("paper","live")
          print("compose_ok")
          PY
