name: build-and-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest
    env:
      # чтобы mypy и import-linter видели пакет из src/
      PYTHONPATH: src

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install "ruff==0.6.9" "mypy==1.11.1" "import-linter==2.0" "pytest==8.3.2"

      - name: Ruff
        run: ruff check .

      # Пока пусть будет advisory. Когда обнулим предупреждения — убери continue-on-error.
      - name: MyPy (advisory)
        continue-on-error: true
        run: mypy src

      # Жёсткая проверка архитектурных контрактов.
      - name: Import Linter
        run: lint-imports --config importlinter.ini --verbose

      # Минимальные тесты (smoke/архитектурные), без сетей и БД.
      - name: Pytest (smoke)
        run: pytest -q
