name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy import-linter

      - name: Ruff (lint)
        run: ruff check src

      - name: Mypy (types)
        run: mypy src || true  # мягкий режим на время

      - name: Import Linter (architecture)
        run: importlint --config importlinter.ini || true

      - name: Build wheel
        run: |
          python -m pip install build
          python -m build --wheel

      - name: Docker build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: crypto-ai-bot:test