name: ci

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install ruff

      - name: Static checks
        run: |
          python - << 'PY'
          import compileall, pathlib, sys
          ok = compileall.compile_dir('src', force=True, quiet=1)
          sys.exit(0 if ok else 1)
          PY
          ruff check src || true

      - name: Smoke run
        env:
          PYTHONPATH: src
        run: |
          python - << 'PY'
          import asyncio, os, sys, threading, time, socket, urllib.request
          from multiprocessing import Process

          os.environ.setdefault("PORT","8081")
          os.environ.setdefault("MODE","paper")

          def run():
            import uvicorn
            from crypto_ai_bot.app.server import app
            uvicorn.run(app, host="127.0.0.1", port=8081, log_level="error")

          p = Process(target=run, daemon=True)
          p.start()
          time.sleep(2.5)

          for path in ("/health", "/metrics", "/status"):
            with urllib.request.urlopen(f"http://127.0.0.1:8081{path}") as r:
              assert r.status == 200, path

          p.terminate()
          p.join(timeout=3)
          PY
