name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Smoke: migrations on temp DB
        env:
          PYTHONPATH: src
        run: |
          python - <<'PY'
          import os, sqlite3
          os.makedirs('data', exist_ok=True)
          db = 'data/ci-smoketest.sqlite3'
          from crypto_ai_bot.core.storage.migrations.runner import run_migrations
          from crypto_ai_bot.utils.time import now_ms
          conn = sqlite3.connect(db)
          conn.row_factory = sqlite3.Row
          v = run_migrations(conn, now_ms=now_ms(), db_path=db, do_backup=False)
          print("migration_version=", v)
          PY

      - name: Build Docker (if Dockerfile exists)
        if: hashFiles('Dockerfile') != ''
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: crypto-ai-bot:test

  # (опционально) Линт можно добавить позже, когда появятся конфиги
