name: Crypto AI Bot CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system deps (curl for healthcheck in compose)
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Ruff (format check)
        run: ruff format --check

      - name: Ruff (lint)
        run: ruff check .

      - name: MyPy
        run: mypy --config-file mypy.ini

      - name: Import Linter
        run: lint-imports -c importlinter.ini

      - name: Pytest
        env:
          PYTHONWARNINGS: "error::DeprecationWarning"
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Build wheel
        run: pip wheel . -w dist

      - name: Build Docker image
        run: docker build -t crypto-ai-bot:ci .
