name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install project deps (if any)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Инструменты гейта
          pip install ruff mypy pytest

      - name: Lint (ruff)
        run: |
          # мягкие правила по умолчанию; при наличии pyproject.toml/ruff.toml они будут учтены
          ruff check src/ --output-format github

      - name: Type-check (mypy)
        run: |
          # строгий, но практичный профиль — без падений на сторонних либах
          mypy src/ --install-types --non-interactive --ignore-missing-imports --pretty

      - name: Run tests (pytest) if tests/ exists
        if: ${{ hashFiles('tests/**') != '' }}
        run: |
          pytest -q

      - name: Build Docker image (if Dockerfile exists)
        if: ${{ hashFiles('Dockerfile') != '' }}
        run: |
          docker build -t crypto-ai-bot:ci .
