name: build-and-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Отменяем предыдущие запуски этого же workflow для той же ветки
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-test:
    runs-on: ubuntu-latest

    # ВАЖНО: чтобы import-linter и mypy видели пакет из src/
    env:
      PYTHONPATH: src

    steps:
      - name: Checkout
      # Забираем код репозитория
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # prod-зависимости
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # dev-зависимости
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # инструменты CI (фиксированные версии для воспроизводимости)
          pip install "ruff==0.6.9" "mypy==1.11.1" "import-linter==2.0"

      - name: Ruff
        run: ruff check .

      # Пока в advisory-режиме, чтобы не блокировать мерджи, если остались предупреждения.
      # Как только обнулим — убери строку continue-on-error.
      - name: MyPy (advisory)
        continue-on-error: true
        run: mypy src

      # ЖЁСТКАЯ проверка архитектурных слоёв.
      - name: Import Linter
        run: lint-imports --config importlinter.ini --verbose

      # Если позже решишь добавить тесты:
      # - name: Pytest
      #   run: pytest -q
